# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a897b2d20e3d7280d30ac49ed28fd237477b55057df94d8feb8fafb8eded9ff3619a058f691e0a26b4ba452f72ffa606d7b82293b798e43298ec91b535e2ddd3
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_client_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  twitter_client_id: <%= ENV["TWITTER_CLIENT_ID"] %>
  twitter_client_secret: <%= ENV["TWITTER_CLIENT_SECRET"] %>
  linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
  linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>

test:
  secret_key_base: 5cea7e54f76a605967749d7e43ef5e27888f5c2727704838039b7592cf05b16f2d745e9c4ebbff42c5e860db25f57cefb63487a1229ae4d0c806f68a7cbcb889
  google_client_id: nothing
  google_client_secret: nothing
  github_client_id: notused
  github_client_secret: notused
  facebook_client_id: notused
  facebook_client_secret: notused
  twitter_client_id: notused
  twitter_client_secret: notused
  linkedin_client_id: notused
  linkedin_client_secret: notused

# Do not keep production secrets in the repository,
# instead read values from the environment.

# if you use Heroku upload your secrets to Heroku by 'rake heroku:secrets RAILS_ENV=production'
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_client_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  twitter_client_id: <%= ENV["TWITTER_CLIENT_ID"] %>
  twitter_client_secret: <%= ENV["TWITTER_CLIENT_SECRET"] %>
  linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
  linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
